version: '3'
services:
  app:
    build: .
    container_name: se_397
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: se_397_database
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - doan3_volume:/var/lib/mysql

volumes:
  doan3_volume:
    driver: local